### ISSUE TITLE
Not able to buy domain, getting Error: invalid address 

### ISSUE THREAD

**Issue by dcts** [ensdomains/ens-app#1443]
**Describe the bug**
When trying to purchase a domain, the "request to register" button throws an error.

**To Reproduce**
1. Go to landing page, connnect Metamask 
2. Search for a domain, e.g. "testdomain" and select it (now you are on the route `app.ens.domains/name/testdomain.eth/register`)
3. Increase registration period to 5 years
4. click "request to register" ❌ => DOES NOT WORK

**Expected behavior**
Should continue.

**Screenshots**
Error code thrown inside the console when clicking the button. My metamask is connected so I assume this is a bug:
```
Error: invalid address (argument="address", value="0x0", code=INVALID_ARGUMENT, version=address/5.4.0)
    at e.value (18.7a3bcb0b-3759.chunk.js:2)
    at e.value (18.7a3bcb0b-3759.chunk.js:2)
    at e.value (18.7a3bcb0b-3759.chunk.js:2)
    at p (18.7a3bcb0b-3759.chunk.js:2)
    at e.value (18.7a3bcb0b-3759.chunk.js:2)
    at r.<anonymous> (18.7a3bcb0b-3759.chunk.js:2)
    at f (18.7a3bcb0b-3759.chunk.js:2)
    at Generator._invoke (18.7a3bcb0b-3759.chunk.js:2)
    at Generator.next (18.7a3bcb0b-3759.chunk.js:2)
    at o (18.7a3bcb0b-3759.chunk.js:2)
```

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.2 LTS
- Browser chrome
- Version 97.0.4692.99 (official build) (64-Bit)

**Comment by makoto** [comment]
I am closing this as I can see that testdomain.eth is already registered

**Comment by dcts** [comment]
@makoto yes someone registered testdomain, but the error still exists, try `testdomain1234512345`. I cannot register an ENS domain currently. Still waiting for a solve. 

The error is still the same:
```
instrument.ts:129 fromPromise error:  Error: invalid address (argument="address", value="0x0", code=INVALID_ARGUMENT, version=address/5.5.0)
    at e.value (index.ts:225:28)
    at e.value (index.ts:237:20)
    at e.value (index.ts:241:21)
    at He (index.ts:109:16)
    at e.value (formatter.ts:235:16)
    at r.<anonymous> (base-provider.ts:1717:51)
    at f (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at a (formatter.ts:521:17)
```

**Comment by dcts** [comment]
How come this is only me affected? Seems weird. Sorry it might be also my fault somehow. I have just no clue how to fix this, I tried different browsers but it still happens.
