### ISSUE TITLE
Can not see register UI in Goerli network

### ISSUE THREAD

**Issue by ZaK3939** [ensdomains/ens-app#1451]
**Describe the bug**
Can not see register UI in Goerli network

**To Reproduce**

1. Set Network to **goerli**
2. Click on search
3. Click on register

**Expected behavior**
Register step are showed up

**Screenshots**
![testtest_eth](https://user-images.githubusercontent.com/17355506/158280049-9140e5ac-0c8b-4eb1-bd7c-7a0711860292.png)

**Comment by tinysnowman** [comment]
I see the same thing with Goerli.
Mac
Chrome Version 99.0.4844.74 (Official Build) (x86_64)
MetaMask Version 10.11.1

You can work around it by loading the Register page while connected to Mainnet (assuming name not registered there) and then toggle back to Goerli in MM.

One copy of this info in the console:
Error getting permanent registrar entry Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32000,"message":"execution reverted"}, method="call", transaction={"to":"0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85","data":"0x6352211ea2f537dfc85312fb7e7d57c2195ec1c0ebd5c21ae3609cb7d8c6bb0ff11f8f48","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.3)
    at e.value (main.4641109a-3813.js:2:1400495)
    at e.value (main.4641109a-3813.js:2:1400639)
    at eu (main.4641109a-3813.js:2:1643137)
    at r.<anonymous> (main.4641109a-3813.js:2:1653815)
    at f (main.4641109a-3813.js:2:2296474)
    at Generator._invoke (main.4641109a-3813.js:2:2296262)
    at Generator.throw (main.4641109a-3813.js:2:2296903)
    at u (main.4641109a-3813.js:2:1641695)
13:08:10.683 

Several copies of this error in the console:
fromPromise error:  Error: call revert exception (method="addr(bytes32)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)
    at e.value (main.4641109a-3813.js:2:1400495)
    at e.value (main.4641109a-3813.js:2:1400639)
    at e.value (main.4641109a-3813.js:2:1453894)
    at main.4641109a-3813.js:2:1513900
    at f (main.4641109a-3813.js:2:2296474)
    at Generator._invoke (main.4641109a-3813.js:2:2296262)
    at Generator.next (main.4641109a-3813.js:2:2296903)
    at a (main.4641109a-3813.js:2:1508317)
