### ISSUE TITLE
Cannot modify my content-hash without deleting my avatar field

### ISSUE THREAD

**Issue by wighawag** [ensdomains/ens-app#1520]
**Describe the bug**
I wanted to update my content-hash field but when I click edit, it highlight the avatar field in red and prevent me from confirming the change

I want to keep my avatar field as it and only change the content-hash

**To Reproduce**

1. Go to https://app.ens.domains/name/ronan.eth/details
2. Click on 'ADD/EDIT RECORD'
3. Scroll down to 'content-hash'
4. change it
5. See error

**Expected behavior**
I expect to be able to modify or add a field without requiring to delete/clear another

**Screenshots**
![2022-06-08_1531x500](https://user-images.githubusercontent.com/790580/172612891-4357de6c-0622-4fdb-bf56-c96939b04a11.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome
- Version: Version 99.0.4844.84 (Official Build) (64-bit)

**Comment by wighawag** [comment]
I had a try at debugging your app from my browser and found the caught error:
```
error: TypeError: (0 , n.getNetworkProviderUrl) is not a function at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:237964 at l (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:238500) at Array.map (<anonymous>) at https://app.ens.domains/static/js/SingleName.30abed00-beff4.chunk.js:1:88521 at f (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2413076) at Generator._invoke (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2412864) at Generator.next (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2413505) at n (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2652295) at u (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2652498) at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2652557 at new Promise (<anonymous>) at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2652438 at https://app.ens.domains/static/js/SingleName.30abed00-beff4.chunk.js:1:88683 at https://app.ens.domains/static/js/SingleName.30abed00-beff4.chunk.js:1:88832 at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:245322 at v (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2124863) at w (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2125238) at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:245493 at new Promise (<anonymous>) at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:245466 at https://app.ens.domains/static/js/SingleName.30abed00-beff4.chunk.js:1:90685 at su (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2305485) at xs (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2324374) at t.unstable_runWithPriority (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2477372) at Hi (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2267140) at Es (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2324131) at us (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2315876) at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2267431 at t.unstable_runWithPriority (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2477372) at Hi (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2267140) at Ji (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2267376) at Yi (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2267311) at rs (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2312735) at ba (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2284526) at https://app.ens.domains/static/js/SingleName.30abed00-beff4.chunk.js:1:91107
message: "(0 , n.getNetworkProviderUrl) is not a function"
stack: "TypeError: (0 , n.getNetworkProviderUrl) is not a function\n    at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:237964\n    at l (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:238500)\n    at Array.map (<anonymous>)\n    at https://app.ens.domains/static/js/SingleName.30abed00-beff4.chunk.js:1:88521\n    at f (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2413076)\n    at Generator._invoke (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2412864)\n    at Generator.next (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2413505)\n    at n (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2652295)\n    at u (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2652498)\n    at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2652557\n    at new Promise (<anonymous>)\n    at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2652438\n    at https://app.ens.domains/static/js/SingleName.30abed00-beff4.chunk.js:1:88683\n    at https://app.ens.domains/static/js/SingleName.30abed00-beff4.chunk.js:1:88832\n    at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:245322\n    at v (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2124863)\n    at w (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2125238)\n    at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:245493\n    at new Promise (<anonymous>)\n    at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:245466\n    at https://app.ens.domains/static/js/SingleName.30abed00-beff4.chunk.js:1:90685\n    at su (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2305485)\n    at xs (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2324374)\n    at t.unstable_runWithPriority (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2477372)\n    at Hi (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2267140)\n    at Es (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2324131)\n    at us (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2315876)\n    at https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2267431\n    at t.unstable_runWithPriority (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2477372)\n    at Hi (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2267140)\n    at Ji (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2267376)\n    at Yi (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2267311)\n    at rs (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2312735)\n    at ba (https://app.ens.domains/static/js/main.5b4ff290-beff4.js:2:2284526)\n    at https://app.ens.domains/static/js/SingleName.30abed00-beff4.chunk.js:1:91107"
[[Prototype]]: Error
```

**Comment by makoto** [comment]
That's related to https://github.com/ensdomains/ens-app/issues/1524 which I belived fixed
