### ISSUE TITLE
Registering a name  step 2 never starts, so registration is not possible ;(

### ISSUE THREAD

**Issue by hillar** [ensdomains/ens-app#547]
Brave Version 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)

after "Request to register"  and  transaction confirmed, the step 2 "Wait for a minute" is not triggered and button "Request to register" is not disabled

https://etherscan.io/address/0xe418607009a22d308039834037770978e9be97fa

**Comment by hillar** [comment]
just going to https://app.ens.domains/name/foobaar
results in console:

```
WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for safeTransferFrom
web3.js:585 error getting block details Error: invalid hash (arg="hash", value={"blockHash":"0x0329b7ef98f30234b9e90fffe1787955386304ef0a5965c0a1d811febd74b29d","blockNumber":"0x8cee3c","from":"0x839ec826cbe694f52e8460a29570539c07d10951","gas":"0x1d4c0","gasPrice":"0x4a817c800","hash":"0xe51f504dad3c59baca2339131de380c94d517863468f710217c0b0502c7e3d64","input":"0xa9059cbb000000000000000000000000cb03bfdccb50c9f62ec1c728f264bf453e03713200000000000000000000000000000000000000000000104da2e2217f6c380000","nonce":"0x2","r":"0xc9d1d03b57708020190f48690c473d1c31a5d1ea40ac6f40df7c7473a79f34df","s":"0x53da99d7dc9d5a5b8fb6c432e5ed318e393722e05dd14fa52909a20cb4026cb2","to":"0x238f0eab0263e695cdf7cecd5dd9ebb3082f83ff","transactionIndex":"0x0","v":"0x26","value":"0x0"}, version=4.0.36)
    at Object.a [as throwError] (ethers.min.js:579)
    at D (ethers.min.js:5008)
    at ethers.min.js:5002
    at Array.forEach (<anonymous>)
    at ethers.min.js:5001
    at Object.transactions (ethers.min.js:4993)
    at g (ethers.min.js:4981)
    at C (ethers.min.js:5092)
    at ethers.min.js:5551
registrar.js:507 Error getting permanent registrar entry Error: call exception (address="0xFaC7BEA255a6990f749363002136aF6556b31e04", method="ownerOf(uint256)", args=["0x857d9ba654fcbe4793867a716d701dd8ef3dbc154a4747de15353597141d1b30"], version=4.0.36)
    at Object.a [as throwError] (ethers.min.js:579)
    at ethers.min.js:228
```

**Comment by hillar** [comment]
clicking on ''Request to register" opens popup for transaction (amount 0)
and in console:
```
inpage.js:1 MetaMask - RPC Error: TypeError: Cannot read property 'substr' of undefined
    at chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1:123112
    at Array.map (<anonymous>)
    at chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1:123103
    at Array.map (<anonymous>)
    at t.exports.getGasPrice (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1:123047)
    at t.exports.addTxGasDefaults (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1:47603)
    at t.exports.addUnapprovedTransaction (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1:47218)
    at async t.exports.newUnapprovedTransaction (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1:46221)
    at async t.exports.newUnapprovedTransaction (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1:117244)
    at async chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1:1278922 {code: -32603, message: "TypeError: Cannot read property 'substr' of undefi…ihdkbihmopkbjmoonfanlbfcl/background.js:1:1278922"}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
(anonymous) @ inpage.js:1
We @ inpage.js:1
(anonymous) @ inpage.js:1
value @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
setTimeout (async)
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
(anonymous) @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
(anonymous) @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
b._write @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
o.write @ contentscript.js:1
p @ contentscript.js:1
(anonymous) @ contentscript.js:1
m.emit @ contentscript.js:1
V @ contentscript.js:1
I @ contentscript.js:1
e.push @ contentscript.js:1
_write @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
o.write @ contentscript.js:1
p @ contentscript.js:1
(anonymous) @ contentscript.js:1
m.emit @ contentscript.js:1
V @ contentscript.js:1
I @ contentscript.js:1
e.push @ contentscript.js:1
_write @ contentscript.js:1
e @ contentscript.js:1
(anonymous) @ contentscript.js:1
o.write @ contentscript.js:1
p @ contentscript.js:1
(anonymous) @ contentscript.js:1
m.emit @ contentscript.js:1
V @ contentscript.js:1
I @ contentscript.js:1
e.push @ contentscript.js:1
b._onMessage @ contentscript.js:1
bundle.esm.js:76 Uncaught (in promise) Error: Network error: TypeError: Cannot read property 'substr' of undefined
    at chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1
    at Array.map (<anonymous>)
    at chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1
    at Array.map (<anonymous>)
    at t.exports.getGasPrice (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1)
    at t.exports.addTxGasDefaults (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1)
    at t.exports.addUnapprovedTransaction (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1)
    at async t.exports.newUnapprovedTransaction (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1)
    at async t.exports.newUnapprovedTransaction (chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1)
    at async chrome-extension:/odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js:1
    at new t (bundle.esm.js:76)
    at Object.error (bundle.esm.js:1313)
    at _ (Observable.js:157)
    at g (Observable.js:196)
    at e.value (Observable.js:253)
    at bundle.esm.js:1090
    at Set.forEach (<anonymous>)
    at Object.error (bundle.esm.js:1089)
    at _ (Observable.js:157)
    at g (Observable.js:196)
```

**Comment by hillar** [comment]
in popup editing gas fee and pressing 'confirm' gives no errors, transaction confirmed notification is shown by Brave in short time, but nothing happens with registration process :(

**Comment by makoto** [comment]
Hello.

A few questions.

1. you mean foobar.eth, not foobar?
2. Does it work if you do via Chrome (Brave Metamask extensions stopped working for me since Brave started having their own native wallet to  support BAT token)

**Comment by brantlymillegan** [comment]
Closing due to inactivity

**Comment by edmundedgar** [comment]
Also getting this error, commit tx goes through, 60 seconds counts down, error appears in console, register button never appears
